services:
  users_service_db:
    image: postgres
    env_file:
      user-service/.env
    ports:
      - "5434:5432"
    volumes:
      - users_postgres_data:/var/lib/postgresql
    restart: always
    command: postgres -c max_prepared_transactions=1000
  
  books_service_db:
    image: postgres
    env_file:
      book-service/.env
    ports:
      - "5435:5432"
    volumes:
      - books_postgres_data:/var/lib/postgresql
    restart: always
    command: postgres -c max_prepared_transactions=1000

  coordinator_api:
    build: 
      dockerfile: coordinator/Dockerfile
      context: .
    env_file:
      coordinator/.env
    ports:
      - "8002:8000"
    develop:
      watch:
        - path: ./coordinator/coordinator
          action: rebuild
          target: /app/coordinator
        
        - path: ./common/common
          action: rebuild
          target: /app/common
    working_dir: /app/coordinator
    volumes:
      - ./common:/app/common
      - ./coordinator:/app/coordinator
    command: >
      sh -c "
        uvicorn coordinator.main:app --host 0.0.0.0 --port 8000
      "

  users_api:
    build: 
      dockerfile: user-service/Dockerfile
      context: .
    env_file:
      user-service/.env
    depends_on:
      - users_service_db
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: ./user-service/user_service
          action: rebuild
          target: /app/user-service
        
        - path: ./common/common
          action: rebuild
          target: /app/common
    working_dir: /app/user-service
    volumes:
      - ./common:/app/common
      - ./user-service:/app/user-service
      - ./user-service/migrations:/app/migrations
      - ./user-service/migrations/versions:/app/migrations/versions
    command: >
      sh -c "
        ../wait-for-db.sh &&
        uvicorn user_service.main:app --host 0.0.0.0 --port 8000
      "

  books_api:
    build: 
      dockerfile: book-service/Dockerfile
      context: .
    env_file:
      book-service/.env
    depends_on:
      - books_service_db
    ports:
      - "8001:8000"
    develop:
      watch:
        - path: ./book-service/book_service
          action: rebuild
          target: /app/book-service
        
        - path: ./common/common
          action: rebuild
          target: /app/common
    working_dir: /app/book-service
    volumes:
      - ./common:/app/common
      - ./book-service:/app/book-service
      - ./book-service/migrations:/app/migrations
      - ./book-service/migrations/versions:/app/migrations/versions
    command: >
      sh -c "
        ../wait-for-db.sh &&
        uvicorn book_service.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  users_postgres_data:
  books_postgres_data:
