services:
  db_test:
    image: postgres:15
    env_file:
      - .env.test
    ports:
      - "5433:5432" # use 5433 for the test database
    tmpfs: # auto clean
      - /var/lib/postgresql/data
    restart: always
  
  test:
    build: .
    depends_on:
      - db_test
    env_file:
      - .env.test
    command: >
      sh -c "
        ./wait-for-db.sh &&
        alembic upgrade head &&
        poetry run pytest -v
      "